---
- name: Install sclo-git25
  yum:
    name:
      - sclo-git25
    state: present
    use_backend: yum
  become: true

- name: Enable sclo-git25 globally for all users
  # See https://developers.redhat.com/blog/2014/03/19/permanently-enable-a-software-collection/
  copy:
    src: enable-sclo-git25.sh
    dest: /etc/profile.d/enable-sclo-git25.sh
    mode: u=rwx,g=rx,o=rx
  become: true

- name: Install git
  yum:
    name:
      - sclo-git25-git
    state: present
    use_backend: yum
  become: true

- name: Add global gitconfig configuration
  template:
    src: "global-gitconfig.j2"
    dest: "/opt/rh/sclo-git25/root/etc/gitconfig"
    mode: 0644
  become: true
