---
- name: Remove sclo-git25 packages
  yum:
    name:
      - sclo-git25-git
      - sclo-git25
    state: absent
    use_backend: yum
  become: true

- name: Remove sclo-git25 envvars for all users
  file:
    dest: /etc/profile.d/enable-sclo-git25.sh
    state: absent
    mode: u=rwx,g=rx,o=rx
  become: true

- name: Add wandisco git repository package
  yum:
    name: http://opensource.wandisco.com/centos/7/git/x86_64/wandisco-git-release-7-2.noarch.rpm
    state: present
    use_backend: yum
  become: true

- name: Add wandisco git package
  yum:
    name: git>=2.20
    state: present
    use_backend: yum
  become: true

- name: Add global gitconfig configuration
  template:
    src: "global-gitconfig.j2"
    dest: "/opt/rh/sclo-git25/root/etc/gitconfig"
    mode: 0644
  become: true
