---
- name: Insall Homebrew + Git
  ansible.builtin.include_role:
    name: geerlingguy.mac.homebrew
  vars:
    homebrew_installed_packages: git
# This is overwritten by our group_vars (cpp.build-machines) 

- name: Add global gitconfig configuration
  ansible.builtin.template:
    src: "global-gitconfig.j2"
    dest: "{{ (ansible_machine == 'arm64') | ternary('/opt/homebrew', '/usr/local') }}/etc/gitconfig"
    mode: 0644
  become: true
