---
- name: Install Git
  community.general.homebrew:
    name:
      - git

- name: Add global gitconfig configuration
  ansible.builtin.template:
    src: "global-gitconfig.j2"
    dest: "{{ (ansible_machine == 'arm64') | ternary('/opt/homebrew', '/usr/local') }}/etc/gitconfig"
    mode: 0644
  become: true
