---
- name: Ensure Chocolatey is installed
  chocolatey.chocolatey.win_chocolatey:
    name: chocolatey
    state: present

- name: Install git
  chocolatey.chocolatey.win_chocolatey:
    name:
      - git.install
    state: present
